### ISSUE TITLE
error Exit status 134

### ISSUE THREAD

**Issue by FreelancePentester** [zhuyingda/veneno#4]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'spider' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prespider', 'spider', 'postspider' ]
5 info lifecycle veneno@0.0.3~prespider: veneno@0.0.3
6 silly lifecycle veneno@0.0.3~prespider: no script for prespider, continuing
7 info lifecycle veneno@0.0.3~spider: veneno@0.0.3
8 verbose lifecycle veneno@0.0.3~spider: unsafe-perm in lifecycle true
9 verbose lifecycle veneno@0.0.3~spider: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ddos/Desktop/veneno/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle veneno@0.0.3~spider: CWD: /home/ddos/Desktop/veneno
11 silly lifecycle veneno@0.0.3~spider: Args: [ '-c', 'node test/spider.js' ]
12 silly lifecycle veneno@0.0.3~spider: Returned: code: 134  signal: null
13 info lifecycle veneno@0.0.3~spider: Failed to exec spider script
14 verbose stack Error: veneno@0.0.3 spider: `node test/spider.js`
14 verbose stack Exit status 134
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid veneno@0.0.3
16 verbose cwd /home/ddos/Desktop/veneno
17 error Linux 4.4.0-53-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "spider"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error veneno@0.0.3 spider: `node test/spider.js`
22 error Exit status 134
23 error Failed at the veneno@0.0.3 spider script 'node test/spider.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the veneno package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node test/spider.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs veneno
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls veneno
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by zhuyingda** [comment]
any system , node version infos?

**Comment by FreelancePentester** [comment]
OS: Linux Mint 18
2 info using npm@3.10.8
3 info using node@v6.9.1

**Comment by zhuyingda** [comment]
I have the same npm and node version on linux centos 6.3. It seems like you can not visit the http://xiao.youxi.com in the test/spider.js . Try to view it in your browser and maybe you can edit the test/spider.js to crawl another website you want.
